#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=30 blur_radius=20 color=0xbf282a36

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:12.0"
  label.font="Hack Nerd Font:Bold:10.0"
  icon.color=0xfff8fbf2
  label.color=0xfff8fbf2
  icon.padding_left=6
  icon.padding_right=2
  label.padding_left=2
  label.padding_right=6
  background.color=0xff6272A4
  background.corner_radius=2
  background.height=20
  background.drawing=on
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

# SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
# for i in "${!SPACE_ICONS[@]}"
# do
#   sid="$(($i+1))"
#   space=(
#     space="$sid"
#     icon="${SPACE_ICONS[i]}"
#     icon.padding_left=7
#     icon.padding_right=7
#     background.color=0x40ffffff
#     background.corner_radius=5
#     background.height=25
#     label.drawing=off
#     script="$PLUGIN_DIR/space.sh"
#     click_script="yabai -m space --focus $sid"
#   )
#   sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
# done

sketchybar --add event aerospace_workspace_change

sketchybar --add item aerospace left \
            --set aerospace icon= icon.color=0xffBD93F9 \
            background.height=2 background.y_offset=-8 background.color=0xffBD93F9 background.drawing=on \
            script="$PLUGIN_DIR/aerospace.sh" \
            --subscribe aerospace aerospace_workspace_change

# for sid in $(aerospace list-workspaces --all); do
#     sketchybar --add item space.$sid left \
#         --set space.$sid \
#         background.height=2 \
#         background.y_offset=-8 \
#         background.color=0xffBD93F9 \
#         background.drawing=off \
#         icon="$sid" \
#         icon.padding_left=4 \
#         icon.padding_right=4 \
#         label.drawing=off \
#         click_script="aerospace workspace $sid" \
#         update_freq=1 \
#         script="$CONFIG_DIR/plugins/aerospace.sh $sid"
# done

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item chevron left \
           --set chevron icon= icon.color=0xffffbb6c label.drawing=off background.drawing=off \
           --add item front_app left \
           --set front_app icon.drawing=off background.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched \
           --subscribe front_app aerospace_workspace_change

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
           --set clock update_freq=10 icon= icon.color=0xffF1FA8C script="$PLUGIN_DIR/clock.sh" \
\
           --add item volume right \
           --set volume icon.color=0xffbd93f9 script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
\
           --add item battery right \
           --set battery update_freq=120 icon.color=0xffFF79C6 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change \
\
           --add item disk right \
           --set disk update_freq=120 icon= icon.color=0xffFFB86C script="$PLUGIN_DIR/disk.sh" \
\
           --add item ram right \
           --set ram update_freq=2 icon= icon.color=0xff50FA7B script="$PLUGIN_DIR/ram.sh" \
\
           --add item cpu right \
           --set cpu update_freq=2 icon= icon.color=0xff8BE9FD script="$PLUGIN_DIR/cpu.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
